### PR TITLE
created a c program to compare the runtime of merge sort , heap sort and quick sort

### PR DESCRIPTION
**Pull request by siddhartthecoder**

### CODE REVIEW

**Comment by thetaniyagupta** [comment]
> Can you location of your file to open challenge folder.

Can you location of your file to open challenge folder.

**Comment by thetaniyagupta** [comment]
> _No description provided._

Hi Can you please change location of your file to open challenge folder.

**Comment by siddhartthecoder** [comment]
> > _No description provided._
> 
> Hi Can you please change location of your file to open challenge folder.

yes sure

**Comment by siddhartthecoder** [comment]
I have doe as you directed

**Pull request merged**
