### PR TITLE
Create UnionFind.py

### PR DESCRIPTION
**Pull request by matheusjustino**

### CODE REVIEW

**Comment by thetaniyagupta** [comment]
> _No description provided._

Can you please change location to solutions/open challenge subdirectory.

**Comment by matheusjustino** [comment]
Why did you don't accepted my contribution?

Em qui, 18 de out de 2018 às 13:37, TANIYA GUPTA <notifications@github.com>
escreveu:

**Comment by cclauss** [comment]
It changed no files....  Click on __files__ above.

**Comment by matheusjustino** [comment]
I'm sorry, i'm newbie in github and don't understand what you said

Em qui, 25 de out de 2018 às 10:35, cclauss <notifications@github.com>
escreveu:

**Comment by cclauss** [comment]
Scroll to the top of this page and click on this

no files were changed

There were no files changed in this pull request so it does not really help (or hurt).  Please open another PR and try again.

**Pull request merged**
